export interface Ichuto{
    idChuto?: number;
    chuto?: string;
    descripcion?: string;
    codigoCliente?: string;
    fkTransportista?: number;
    codigoTransportista?: string;
    tipoFlota?: string;
    capacidad?: number;
    modelo?: string;
    marca?: string;
    fechaVencimientoPoliza?: Date;
    fechaInclusion?: Date;
    flota?: string;
    propietario?: string;
    ced_propietario?: string;
    tipo_propietario?: string;
    estado?: string;
    tara?: number;
    year?: number;
    neto_max?: number;
    tara_minima?: number;
    tara_maxima?: number;
    ultimo_conductor_cedula?: string;
    ultimo_conductor_fecha_acceso?: Date;
    ultima_batea?: string;
    regular?: string;
    exclusivo?: string;
    ejes?: number;
    multicarga?: string;
    statusChuto?: number    
 }