export interface Imaterial{
    idMaterial?: number;
    codigoMaterial?: string;
    descripcionMaterial?: string;
    fkTipoMaterial?: number;
    densidad?: number;
    precio?: number;
    fkUnidad?: number;
    fkUbicacionMaterial?: number;
    cantidadDisponible?: number;
    asignarTara?: number;
    maximaToneladaXVehiculo?: number;
    semiElaborado?: number;
    instalacion?: string;
    ensayo?: string;
    chatarra?: number;
    familia?: string;
    permitirExcesoPeso?: number;
    preparada?: number;
    densidadMinima?: number;
    densidadMaxima?: number;
    codigoSap?: string;
    origen?: string;
    fechaCreacion?: Date;
    gas?: number;
    ownerRecord?: string;
    cup?: string;
    efectuarPesajeControl?: number;
    statusMaterial?: number
 }